[package]
name = "txflow"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
csv = "1.3"
rust_decimal = { version = "1.37.1", features = ["serde", "macros"] }
